### ISSUE TITLE
EPIC: Introduce integration and end-to-end tests (1/5)

### ISSUE THREAD

**Issue by xinyao-song** [ucsb-cs156-s24/proj-gauchoride-s24-5pm-8#31]
### As a...

developer

### I can...

run integration and end-to-end tests

### So that...

my test suite is more comprehensive

### Discussion

Right now the test suite contains only unit tests. 

We want to add integration tests and end-to-end tests slowly into the application.

This epic involves adding all of the necessary setup to allow for the addition of integration and end-to-end tests.

This guide [Going Beyond Unit Tests](https://ucsb-cs156.github.io/topics/spring_react/spring_react_testing_pyramid.html) covers every step of the process in detail. Please follow it and adapt as necessary since the guide was based on proj-happycows.

You may find the pull request for that tutorial [here](https://github.com/ucsb-cs156/proj-happycows/pull/107). 

### Acceptance Criteria

- [ ] Developer can use a series of commands specified in the guide to run the integration and end-to-end test suite.

### Implementation Todos

Issue 1 :  (Step 1 and 2 in the guide)
- [ ] Modify `pom.xml` with the necessary dependencies and new Maven profiles
- [ ] Add some `.properties` files for the new Spring profiles
